[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.0.2" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version="0.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.16" }
wally = { source = "UpliftGames/wally", version = "0.3.1"}