[package]
name = "chipioindustries/rapscallion"
description = "Easily travel long paths/routes in the datamodel in various ways."
version = "1.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Llama = "freddylist/llama@1.1.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"